version: "3"
services:
  caddy:
    # image: myCaddy
    build:
      context: .
    container_name: myCaddy
    ports:
      - "80:80"
      - "443:443"
      - "2015:2015"
    # volumes:
    #   - $PWD/build:/srv
      # - $PWD/Caddyfile:/etc/
      # - $HOME/.caddy:/root/.caddy
